services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=book'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - livros_data:/var/lib/postgresql/data

volumes:
  livros_data: